services:
  - type: web
    name: lilith-cats
    runtime: node
    plan: free
    buildCommand: npm install && npm run build && npm install -g serve
    startCommand: serve dist -l $PORT
    envVars:
      - key: NODE_VERSION
        value: 22
