services:
  - type: web
    name: lilith-cats
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: next start -p $PORT
    envVars:
      - key: NODE_VERSION
        value: 22
